- common/djangoapps/student/forms.py
- lms/templates/organization_register.html
LMS-118: Address 2 line is not a required field.Added an “Already Registered” option.
> Organization Registration Fields

- lms/envs/common.py
- lms/static/js/instructor_dashboard/membership.js
- lms/templates/footer.html
- lms/templates/instructor/instructor_dashboard_2/membership.html
LMS-74- Bulk Enrollment using CSV
LMS-150- Bulk Enrollment without CSV
> LMS 74,LMS-150

- lms/static/js/instructor_dashboard/membership.js
- lms/templates/instructor/instructor_dashboard_2/membership.html
LMS-150: Bulk Enrollment(Non-CSV)
> LMS-150: Bulk Enrollment

- lms/djangoapps/courseware/access.py
- lms/djangoapps/courseware/access_utils.py
- lms/djangoapps/courseware/courses.py
- lms/templates/instructor/instructor_dashboard_2/membership.html
- openedx/core/djangoapps/embargo/api.py
- openedx/features/course_experience/views/course_home.py
Added logger for Course Access Issue and Changes in LMS-224
> Added logger for Course Access Issue

- lms/djangoapps/courseware/access.py
- lms/djangoapps/courseware/courses.py
Adding Logger course access Issue
> Adding Logger course access Issue

- common/djangoapps/student/views/login.py
- lms/djangoapps/courseware/access.py
- lms/djangoapps/courseware/access_utils.py
- lms/djangoapps/courseware/courses.py
- lms/djangoapps/courseware/views/views.py
- openedx/core/djangoapps/embargo/api.py
- openedx/features/course_experience/views/course_home.py
- openedx/features/course_experience/views/course_outline.py
> Resolved Course Access Issue

- common/lib/xmodule/xmodule/seq_module.py
- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
- openedx/features/course_experience/views/course_outline.py
> Added Logger for debugging

- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> Adding logger for debugging

- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> LMS-183 Changes done

- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> Added Loggers

- openedx/core/djangoapps/programs/tasks/v1/tasks.py
- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> LMS-183 made changes

- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> LMS-183 Changes

- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> LMS-183 Issue

- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
> LMS-183 Changes 

- lms/templates/header/user_dropdown.html
> user dropdown taking none value

- lms/templates/register-form.html
> Registration Page Markup done

- lms/djangoapps/instructor/views/instructor_dashboard.py
- lms/templates/instructor/instructor_dashboard_2/student_track.html
- lms/templates/organization_register.html
Pagination in Student Progress
> Pagination in Student Progress

- lms/djangoapps/branding/api.py
- lms/djangoapps/ut_new/templates/coherts.html
- lms/envs/common.py
Removed Footer" blog and donate tabs" and Removed Inbound Email from common.py
> Removed Footer "Blog and Donate Tabs"  and Removed Inbound Email

- lms/templates/dashboard/_dashboard_course_listing.html
- openedx/features/course_experience/views/course_outline.py
> Code Refactor

- common/djangoapps/student/views/dashboard.py
- common/djangoapps/student/views/login.py
> Payment Gateway Modification

- ut-custom-themes/ut_theme/lms/templates/courses_list.html
Modification in index.html page
> Modification in index.html page

- lms/djangoapps/instructor/views/api.py
- lms/static/js/instructor_dashboard/membership.js
Bulk Enrollment Changes LMS-238
> Bulk Enrollment Changes LMS-238

- lms/templates/register-form.html
> Register Page Modifications

- common/djangoapps/student/views/dashboard.py
- lms/templates/instructor/instructor_dashboard_2/membership.html
Lms-184 and Bulk Enrollment Page
> Lms-184 and Bulk Enrollment Page

- common/lib/xmodule/xmodule/seq_module.py
- lms/djangoapps/courseware/module_render.py
>  Multiple Choice Error

- common/djangoapps/student/forms.py
- common/djangoapps/student/views/dashboard.py
- common/lib/xmodule/xmodule/seq_module.py
- common/lib/xmodule/xmodule/vertical_block.py
- common/lib/xmodule/xmodule/x_module.py
- lms/djangoapps/courseware/module_render.py
- lms/djangoapps/courseware/views/views.py
- lms/envs/common.py
- lms/static/completion/js/CompletionOnViewService.js
- lms/static/completion/js/ViewedEvent.js
- lms/templates/payment_buy_now.html
- openedx/features/course_experience/utils.py
- openedx/features/course_experience/views/course_outline.py
>  Payment LMS-13 and Tick issue

- lms/djangoapps/cohert_dashboard/dash_render.py
- lms/templates/instructor/instructor_dashboard_2/student_track.html
CSS Changes in Cohert performance tracking dashboard
> CSS Changes in Cohert performance tracking dashboard

- common/djangoapps/student/views/dashboard.py
- lms/djangoapps/courseware/views/views.py
- lms/djangoapps/ut_new/tasks.py
- lms/djangoapps/ut_new/urls.py
- lms/djangoapps/ut_new/views.py
- lms/templates/dashboard.html
- lms/templates/emails/user_records_csv.txt
- lms/templates/header/user_dropdown.html
- lms/urls.py
> Student data tracking

- lms/djangoapps/ut_new/tasks.py
- pip_requirements.txt
> Changed the email subject

- common/lib/xmodule/xmodule/seq_module.py
- common/lib/xmodule/xmodule/vertical_block.py
- pip_requirements.txt
> Block completion Issue

- themes/wgu_theme/lms/templates/seq_module.html
> theme applied

- ut-custom-themes/ut_theme/lms/templates/index.html
> index.html
